# Generated by Django 4.1.5 on 2023-12-28 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Emp",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=10, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("sal", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("job", models.CharField(max_length=50)),
            ],
        ),
    ]
